-- ============================================================================
-- RBAC 系统 PostgreSQL 初始化脚本
--
-- 使用方式（先建库，再在本库中执行本脚本）：
--   1) psql -U postgres -c "CREATE DATABASE rbac_system;"
--   2) psql -U postgres -d rbac_system -f init.sql
--
-- 种子账号：admin / admin123
-- ============================================================================

-- CREATE DATABASE rbac_system;  -- 如尚未建库，取消本行注释执行一次即可

-- ---------------------------------------------------------------------------
-- 表结构（PostgreSQL 方言：IDENTITY 主键 / SMALLINT 状态位 / TIMESTAMP 时间）
-- ---------------------------------------------------------------------------

CREATE TABLE sys_user (
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    username    VARCHAR(50)  NOT NULL UNIQUE,
    password    VARCHAR(100) NOT NULL,                -- BCrypt 加密
    nickname    VARCHAR(50),
    email       VARCHAR(100),
    phone       VARCHAR(20),
    status      SMALLINT     NOT NULL DEFAULT 1,      -- 1 启用 0 禁用
    create_time TIMESTAMP    DEFAULT CURRENT_TIMESTAMP,
    update_time TIMESTAMP
);

CREATE TABLE sys_role (
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    role_name   VARCHAR(50)  NOT NULL,
    role_code   VARCHAR(50)  NOT NULL UNIQUE,
    description VARCHAR(200),
    status      SMALLINT     NOT NULL DEFAULT 1,
    create_time TIMESTAMP    DEFAULT CURRENT_TIMESTAMP,
    update_time TIMESTAMP
);

CREATE TABLE sys_menu (
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    parent_id   BIGINT       NOT NULL DEFAULT 0,
    menu_name   VARCHAR(50)  NOT NULL,
    path        VARCHAR(200),                          -- 前端路由地址
    component   VARCHAR(200),                          -- 前端组件路径（相对 src/views，不含 .vue）
    perms       VARCHAR(100),                          -- 权限标识，如 system:user:list
    icon        VARCHAR(50),
    type        SMALLINT     NOT NULL,                 -- 0 目录 1 菜单 2 按钮
    sort        INT          NOT NULL DEFAULT 0,
    status      SMALLINT     NOT NULL DEFAULT 1,
    create_time TIMESTAMP    DEFAULT CURRENT_TIMESTAMP
);

CREATE INDEX idx_sys_menu_parent_id ON sys_menu (parent_id);

CREATE TABLE sys_user_role (
    user_id BIGINT NOT NULL,
    role_id BIGINT NOT NULL,
    PRIMARY KEY (user_id, role_id)
);

CREATE TABLE sys_role_menu (
    role_id BIGINT NOT NULL,
    menu_id BIGINT NOT NULL,
    PRIMARY KEY (role_id, menu_id)
);

-- ---------------------------------------------------------------------------
-- 种子数据：角色
-- ---------------------------------------------------------------------------

INSERT INTO sys_role (id, role_name, role_code, description) VALUES
    (1, '系统管理员', 'ROLE_ADMIN', '拥有全部权限'),
    (2, '普通用户',   'ROLE_USER',  '仅基础访问权限')
ON CONFLICT (id) DO NOTHING;

-- ---------------------------------------------------------------------------
-- 种子数据：菜单树（type: 0 目录 1 菜单 2 按钮）
-- component 相对前端 src/views 目录，不含 ".vue"
-- ---------------------------------------------------------------------------

INSERT INTO sys_menu (id, parent_id, menu_name, path, component, perms, icon, type, sort) VALUES
    (1,  0, '仪表盘',   '/dashboard',   'dashboard/index',   NULL,                 'Odometer', 1, 1),
    (2,  0, '系统管理', NULL,           NULL,                NULL,                 'Setting',  0, 2),
    (3,  2, '用户管理', '/system/user', 'system/user/index', 'system:user:list',   'User',     1, 1),
    (4,  3, '用户新增', NULL,           NULL,                'system:user:add',    NULL,       2, 1),
    (5,  3, '用户修改', NULL,           NULL,                'system:user:edit',   NULL,       2, 2),
    (6,  3, '用户删除', NULL,           NULL,                'system:user:delete', NULL,       2, 3),
    (7,  3, '重置密码', NULL,           NULL,                'system:user:resetPwd', NULL,     2, 4),
    (8,  3, '分配角色', NULL,           NULL,                'system:user:assignRole', NULL,   2, 5),
    (9, 2, '菜单管理', '/system/menu', 'system/menu/index', 'system:menu:list',   'Menu',     1, 2),
    (10, 9, '菜单新增', NULL,           NULL,                'system:menu:add',    NULL,       2, 1),
    (11, 9, '菜单修改', NULL,           NULL,                'system:menu:edit',   NULL,       2, 2),
    (12, 9, '菜单删除', NULL,           NULL,                'system:menu:delete', NULL,       2, 3),
    (13, 2, '角色管理', '/system/role', 'system/role/index', 'system:role:list',   'Avatar',   1, 3),
    (14, 13, '分配菜单', NULL,          NULL,                'system:role:assignMenu', NULL,   2, 1)
ON CONFLICT (id) DO NOTHING;

-- ---------------------------------------------------------------------------
-- 种子数据：管理员账号（admin / admin123）
-- 该哈希与 PasswordHashTest 中的 ADMIN_HASH 常量保持一致
-- ---------------------------------------------------------------------------

INSERT INTO sys_user (id, username, password, nickname, email, status) VALUES
    (1, 'admin', '$2a$10$6Q.0i0obqZEV8ak5bWUpB.7iXDsL4.YDf53SuEJIfw2/eZch/2xDe',
     '超级管理员', 'admin@example.com', 1)
ON CONFLICT (id) DO NOTHING;

-- ---------------------------------------------------------------------------
-- 关联：admin -> ROLE_ADMIN；ROLE_ADMIN 拥有全部菜单；ROLE_USER 仅仪表盘
-- ---------------------------------------------------------------------------

INSERT INTO sys_user_role (user_id, role_id)
    SELECT 1, 1 WHERE NOT EXISTS (SELECT 1 FROM sys_user_role WHERE user_id = 1 AND role_id = 1);

INSERT INTO sys_role_menu (role_id, menu_id)
    SELECT 1, m.id FROM sys_menu m
    WHERE NOT EXISTS (SELECT 1 FROM sys_role_menu WHERE role_id = 1 AND menu_id = m.id);

INSERT INTO sys_role_menu (role_id, menu_id)
    SELECT 2, 1 WHERE NOT EXISTS (SELECT 1 FROM sys_role_menu WHERE role_id = 2 AND menu_id = 1);

-- 显式插入固定 ID 后，将序列拨到最大值，保证后续自增不冲突
SELECT setval(pg_get_serial_sequence('sys_menu', 'id'), (SELECT MAX(id) FROM sys_menu));
SELECT setval(pg_get_serial_sequence('sys_role', 'id'), (SELECT MAX(id) FROM sys_role));
SELECT setval(pg_get_serial_sequence('sys_user', 'id'), (SELECT MAX(id) FROM sys_user));
